theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true

deployment:
  targets:
    name: "scaleway.osuny.org"
    URL: "s3://scaleway.osuny.org?endpoint=https://s3.fr-par.scw.cloud&region=fr-par"

params:
  breadcrumb:
    position: after-hero
  posts:
    list:
      layout: list
  organizations:
    dark_logo_background: true