name: Compilation et déploiement

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    name: Compilation du site Hugo et déploiement sur Scaleway Object Storage
    runs-on: ubuntu-latest
    steps:
    - name: Récupération des données
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Mise en place de Hugo
      uses: peaceiris/actions-hugo@v2.6.0
      with:
        hugo-version: 'latest'
        extended: true
    - name: Compilation du site
      run: hugo
    - name: Déploiement sur Scaleway Object Storage
      run: hugo deploy --force --maxDeletes -1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_SECRET_ACCESS_KEY }}
